### ISSUE TITLE

Lushan Botanical Garden - Lushan


### ISSUE THREAD

**Issue by gbif-collections** [gbif/collections-duplicates#35]
[Duplicates](https://registry.gbif.org/institution/search?name=Lushan+Botanical+Garden&city=Lushan) found for: 
- Same name: `Lushan Botanical Garden`
- Same city: `Lushan`

[Lushan Botanical Garden - LBG](https://registry.gbif.org/institution/ed726c57-f1e3-4ad1-a024-5c2df11dc362)
```

Key: ed726c57-f1e3-4ad1-a024-5c2df11dc362
Code: LBG
Name: Lushan Botanical Garden
Physical country: CHINA
Physical city: Lushan
Mailing country: CHINA
Mailing city: Lushan
Active: true
Is IH: true
Is IDigBio: false
```
[Lushan Botanical Garden - LUS](https://registry.gbif.org/institution/81731421-ac7f-495d-a176-8bdf7f38648a)
```

Key: 81731421-ac7f-495d-a176-8bdf7f38648a
Code: LUS
Name: Lushan Botanical Garden
Physical country: CHINA
Physical city: Lushan
Mailing country: CHINA
Mailing city: Lushan
Active: false
Is IH: true
Is IDigBio: false
```

**Comment by ManonGros** [comment]
Merged, description said "LUS same as LBG. Use LBG."
